'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slides=$$('.slide');let current=0,muted=true,lastNav=0,lastAction=Date.now(),activeFeatures=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const stamps=new Set();
console.log(`====================================\nRUBRIK WILDLIFE PARK SYSTEM\n====================================\nPark Status       : ONLINE\nHabitats          : 6\nDatabase          : Google Sheets\nAdditional Cost   : Rp 0\nRanger Mood       : Depends on audience attention\nWarning           : Do not feed production data\n====================================`);
const habitats=[['Pengumuman','Eagle Announcement Tower','Eagle','🦅'],['Koran Harian','Owl News Library','Owl','🦉'],['Obrolan Warkop','Meerkat Social Burrow','Meerkat','🦫'],['Lapak Jualan','Monkey Market Street','Monkey','🐒'],['Agenda','Elephant Calendar Garden','Elephant','🐘'],['Factory Wire','Cheetah Express Track','Cheetah','🐆']];
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
function beep(f=520,d=.06){if(muted)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;o.connect(g);g.connect(a.destination);g.gain.value=.035;o.start();o.stop(a.currentTime+d)}catch{}}
function openHabitatGate(){slides[0].classList.add('open');toast('Ranger guide: Welcome to RuBrik Wildlife Park.')}function closeHabitatGate(){slides[0].classList.remove('open')}function animateAnimalEntrance(){slides[current].querySelector('.mascot')?.animate?.([{transform:'translateY(12px)',opacity:.7},{transform:'translateY(0)',opacity:1}],{duration:420})}function drawSafariRoute(){updateProgress()}function revealFootprints(){document.body.classList.add('footprints')}function swingWoodenSign(){slides[current].querySelector('h2')?.animate?.([{transform:'rotate(-1deg)'},{transform:'rotate(1deg)'},{transform:'none'}],{duration:420})}function focusBinoculars(){toast('Binocular focus locked on '+slides[current].dataset.zone)}function launchWildlifeConfetti(n=150){confetti(n)}function awardSafariStamp(name){if(!name||stamps.has(name))return;stamps.add(name);const s=document.createElement('div');s.className='stamp';s.textContent=name;$('#stampShelf').appendChild(s);toast('Safari stamp: '+name)}function activateManagementTour(on){document.body.classList.toggle('tour-mode',on);toast(on?'Management Tour Mode enabled':'WILDLIFE RESTORED')}function releasePanicMonkey(){document.body.classList.remove('monkey-release');void document.body.offsetWidth;document.body.classList.add('monkey-release');toast('Relax. It is only a presentation.');setTimeout(()=>document.body.classList.remove('monkey-release'),1900)}
Object.assign(window,{openHabitatGate,closeHabitatGate,animateAnimalEntrance,drawSafariRoute,revealFootprints,swingWoodenSign,focusBinoculars,launchWildlifeConfetti,awardSafariStamp,activateManagementTour,releasePanicMonkey});
function go(i,force=false){if(i<0||i>=slides.length)return;if(!force&&Date.now()-lastNav<260)return;lastNav=Date.now();slides[current].classList.remove('active');current=i;slides[current].classList.add('active');$('#counter').textContent=`HABITAT ${String(current+1).padStart(2,'0')} / ${slides.length}`;$('#zoneName').textContent=slides[current].dataset.zone;updateProgress();awardSafariStamp(slides[current].dataset.stamp);animateAnimalEntrance();swingWoodenSign();lastAction=Date.now();beep(360+current*18)}
function updateProgress(){const pct=(current+1)/slides.length*100;$('#progressLine').style.width=pct+'%';$('#jeep').style.left=`calc(${pct}% - 26px)`}function next(){go(Math.min(slides.length-1,current+1))}function prev(){go(Math.max(0,current-1))}
function buildMap(){const z=$('.zoo-map');if(z&&!z.dataset.ready){habitats.forEach((h,i)=>{const n=document.createElement('article');n.className='habitat-node';n.style.left=[8,66,8,66,36,36][i]+'%';n.style.top=[4,4,66,66,0,78][i]+'%';n.innerHTML=`<b>${h[3]} ${h[1]}</b><br><small>${h[0]} — ${h[2]}</small>`;z.appendChild(n)});z.dataset.ready=1}}
buildMap();habitats.forEach((h,i)=>$('#featureCards').insertAdjacentHTML('beforeend',`<button class="feature-card" type="button"><b>${h[3]} ${h[1]}</b><br><small>${h[0]} habitat inactive</small></button>`));$$('.feature-card').forEach((card,i)=>card.onclick=()=>{if(card.classList.contains('active'))return;card.classList.add('active');card.querySelector('small').textContent='Habitat lights on — stamp awarded';activeFeatures++;$('#featureMeter').style.width=(activeFeatures/6*100)+'%';awardSafariStamp(habitats[i][1]);beep(650,.08);if(activeFeatures===6){$('#featureAchievement').textContent='THE PARK IS FULLY OPERATIONAL';confetti(80)}});
function confetti(n=180){const c=$('#confettiCanvas'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;n=reduced?Math.min(n,40):n;const shapes=['🍃','🎟','🐾','◦'];let a=Array.from({length:n},()=>({x:Math.random()*c.width,y:-30,v:2+Math.random()*6,w:Math.random()*4-2,s:12+Math.random()*18,t:shapes[Math.floor(Math.random()*shapes.length)],col:['#55b86b','#f39a4a','#8ed8f8','#f5dfb5','#4285f4','#ea4335','#fbbc04','#34a853'][Math.floor(Math.random()*8)]}));let f=0;(function loop(){x.clearRect(0,0,c.width,c.height);a.forEach(p=>{p.y+=p.v;p.x+=p.w;x.fillStyle=p.col;x.font=p.s+'px serif';x.fillText(p.t,p.x,p.y)});if(f++<170)requestAnimationFrame(loop);else x.clearRect(0,0,c.width,c.height)})()}
function overview(){const o=$('#overview');if(o.style.display==='grid'){o.style.display='none';o.setAttribute('aria-hidden','true');return}o.innerHTML='';slides.forEach((s,i)=>{const b=document.createElement('button');b.textContent=`${i+1}. ${s.dataset.zone}`;b.onclick=()=>{o.style.display='none';o.setAttribute('aria-hidden','true');go(i,true)};o.appendChild(b)});o.style.display='grid';o.setAttribute('aria-hidden','false')}
$('#startBtn').onclick=()=>{muted=false;$('#soundBtn').textContent='Sound On';$('#soundBtn').setAttribute('aria-pressed','true');openHabitatGate();setTimeout(next,520)};$('#overviewBtn').onclick=overview;$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();$('#soundBtn').onclick=()=>{muted=!muted;$('#soundBtn').textContent=muted?'Sound Off':'Sound On';$('#soundBtn').setAttribute('aria-pressed',String(!muted));toast(muted?'Sound muted':'Soft safari ambience enabled')};$('#tourToggle').onchange=e=>activateManagementTour(e.target.checked);$('#panicBtn').onclick=releasePanicMonkey;$('#breakingBtn').onclick=()=>{$('.ticker').classList.add('fast');$('#breakingMsg').style.color='#fff06a';toast('Breaking News Mode activated');beep(920,.16)};$('#engBtn').onclick=()=>$('#archList').innerHTML='<li>landing.gs</li><li>cms.gs</li><li>rss-fetcher.gs</li><li>email-fetcher.gs</li>';$('#mgmtBtn').onclick=()=>$('#archList').innerHTML='<li>Employee portal</li><li>Admin dashboard</li><li>Automation engine</li><li>Central data source</li>';$('#approveBtn').onclick=()=>{$('#pending').textContent=Math.max(0,+$('#pending').textContent-1);$('#published').textContent=+$('#published').textContent+1;awardSafariStamp('Ranger Approval');toast('Green ranger stamp applied')};$('#dangerBtn').onclick=()=>toast('Congratulations. You found the feature requested five minutes before demo.');$('#runaway').onpointerenter=e=>{e.target.style.transform=`translate(${Math.random()*260-130}px,${Math.random()*130-65}px)`};$$('.quadrants button').forEach((b,i)=>b.onclick=()=>{$('#gauge').style.width=(i+1)*25+'%';b.classList.add('active')});function finalShow(){confetti(760);awardSafariStamp('Wildlife Park Operator');$('#finalMsg').style.display='block';toast('THE PARK IS OPEN. DEPLOYMENT BEGINS.')}$('#activateBtn').onclick=finalShow;$('#replayBtn').onclick=finalShow;$('#quiz').onclick=e=>{if(e.target.tagName==='BUTTON'){$('#quizResult').textContent='Semua jawaban benar';confetti(40)}};
addEventListener('keydown',e=>{lastAction=Date.now();if(e.target.matches('input,button'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();next()}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();prev()}if(e.key==='Home')go(0,true);if(e.key==='End')go(slides.length-1,true);if(e.key==='Escape')overview();if(e.key.toLowerCase()==='f')$('#fullscreenBtn').click();if(e.key.toLowerCase()==='m')$('#soundBtn').click();if(e.key.toLowerCase()==='q')$('#quiz').style.display='grid';if(/^[1-9]$/.test(e.key))go(+e.key-1,true);if(e.key==='0')go(9,true)});
let wheel=0;addEventListener('wheel',e=>{if(Date.now()-wheel<750)return;wheel=Date.now();e.deltaY>0?next():prev()},{passive:true});let sx=0;addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>55)(dx<0?next:prev)()},{passive:true});document.addEventListener('visibilitychange',()=>document.body.classList.toggle('paused',document.hidden));setInterval(()=>{if(Date.now()-lastAction>30000){document.body.classList.add('sleepy');toast('Audience activity not detected. Possible causes: meeting fatigue or snack shortage.');lastAction=Date.now()}},5000);addEventListener('pointerdown',e=>{lastAction=Date.now();document.body.classList.remove('sleepy');if(e.target.classList.contains('slide'))toast(['Please do not feed the old process.','Information should have a habitat, not a rumor.','The elephant remembers your meeting. Unfortunately.','No spreadsheet rows were harmed during this demo.','Finance has approved this habitat.'][Math.floor(Math.random()*5)])});
go(0,true);

const mascotSVG={
 eagle:`<svg viewBox="0 0 180 180" role="img" aria-label="Original eagle mascot"><path d="M28 92c28-42 55-46 72-17 15-18 34-18 52 5-18 5-26 18-34 38-23-10-43-9-66 3-5-18-12-27-24-29z" fill="#8ed8f8"/><path d="M72 63l28-26 26 28c-18-8-36-8-54-2z" fill="#f5dfb5"/><circle class="eye" cx="82" cy="78" r="5"/><circle class="eye" cx="109" cy="78" r="5"/><path d="M94 88l12 0-7 10z" fill="#e8792d"/></svg>`,
 owl:`<svg viewBox="0 0 180 180" role="img" aria-label="Original owl mascot"><path d="M45 58c10-26 78-26 90 0 15 34 0 84-45 86-45-2-60-52-45-86z" fill="#18384a"/><circle cx="73" cy="79" r="22" fill="#f5dfb5"/><circle cx="107" cy="79" r="22" fill="#f5dfb5"/><circle class="eye" cx="73" cy="79" r="6"/><circle class="eye" cx="107" cy="79" r="6"/><path d="M88 92l10 0-5 9z" fill="#f39a4a"/></svg>`,
 meerkat:`<svg viewBox="0 0 180 180" role="img" aria-label="Original meerkat mascot"><path d="M68 58c0-22 44-22 44 0v72c0 24-44 24-44 0z" fill="#d8b277"/><path d="M61 52h58l-15-22-14 16-14-16z" fill="#f5dfb5"/><circle class="eye" cx="80" cy="69" r="5"/><circle class="eye" cx="100" cy="69" r="5"/><path class="line" d="M84 88c7 6 13 6 20 0"/></svg>`,
 monkey:`<svg viewBox="0 0 180 180" role="img" aria-label="Original monkey mascot"><circle cx="90" cy="86" r="48" fill="#9a642f"/><circle cx="47" cy="86" r="21" fill="#d8b277"/><circle cx="133" cy="86" r="21" fill="#d8b277"/><ellipse cx="90" cy="101" rx="31" ry="24" fill="#f5dfb5"/><circle class="eye" cx="75" cy="78" r="5"/><circle class="eye" cx="105" cy="78" r="5"/><path class="line" d="M80 107c9 8 20 8 29 0"/></svg>`,
 elephant:`<svg viewBox="0 0 180 180" role="img" aria-label="Original elephant mascot"><circle cx="90" cy="82" r="43" fill="#b7c3c8"/><circle cx="45" cy="85" r="28" fill="#aab7bd"/><circle cx="135" cy="85" r="28" fill="#aab7bd"/><path d="M83 105c2 42 35 30 25 10-8 12-14 3-13-10z" fill="#b7c3c8"/><circle class="eye" cx="76" cy="76" r="5"/><circle class="eye" cx="104" cy="76" r="5"/></svg>`,
 cheetah:`<svg viewBox="0 0 180 180" role="img" aria-label="Original cheetah mascot"><path d="M36 101c18-40 89-51 111-10-17 29-81 43-111 10z" fill="#f0bd4f"/><circle cx="122" cy="74" r="25" fill="#f0bd4f"/><circle class="eye" cx="130" cy="70" r="5"/><g fill="#10251d"><circle cx="72" cy="91" r="5"/><circle cx="94" cy="104" r="4"/><circle cx="112" cy="94" r="4"/></g><path class="line" d="M142 82c12 1 18 5 22 12"/></svg>`,
 beaver:`<svg viewBox="0 0 180 180" role="img" aria-label="Original beaver mascot"><circle cx="90" cy="82" r="42" fill="#8a552a"/><ellipse cx="90" cy="132" rx="38" ry="18" fill="#d8b277"/><rect x="75" y="98" width="12" height="18" fill="#fff5dc"/><rect x="93" y="98" width="12" height="18" fill="#fff5dc"/><circle class="eye" cx="75" cy="76" r="5"/><circle class="eye" cx="105" cy="76" r="5"/><path class="line" d="M80 58h46"/></svg>`
};
$$('.mascot').forEach(el=>{const k=Object.keys(mascotSVG).find(k=>el.classList.contains(k+'-svg')); if(k) el.innerHTML=mascotSVG[k];});
