'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slides=$$('.slide');let current=0,muted=false,drawing=false,eraser=false,color='#f7f0d4',lastAction=Date.now(),strokes=[],curStroke=[];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
console.log(`====================================\nRUBRIK BLACKBOARD CONTROL SYSTEM\n====================================\nStatus              : ONLINE\nDatabase            : Google Sheets\nAdditional Cost     : Rp 0\nTeacher Mood        : Depends on audience attention\nSpreadsheet Warning : Do not sort production columns\n====================================`);
const toast=t=>{const el=$('#toast');el.textContent=t;el.style.cssText='position:fixed;z-index:200;left:50%;top:78px;transform:translateX(-50%);background:#111;color:#ffd75a;border:2px dashed #fff;padding:12px 18px;border-radius:999px;font:700 20px Patrick Hand';clearTimeout(toast.t);toast.t=setTimeout(()=>el.textContent='',2600)};
const beep=(f=520,d=.09)=>{if(muted)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;o.connect(g);g.connect(a.destination);g.gain.value=.05;o.start();o.stop(a.currentTime+d)}catch(e){}};
window.ChalkDraw={write:(el,txt=el.textContent)=>{if(reduced)return;el.textContent='';[...txt].forEach((c,i)=>setTimeout(()=>el.textContent+=c,i*28))},drawPath:p=>{try{const l=p.getTotalLength();p.style.strokeDasharray=l;p.style.strokeDashoffset=l;p.getBoundingClientRect();p.style.transition='stroke-dashoffset 1s';p.style.strokeDashoffset=0}catch(e){}},drawBox:el=>el.classList.add('chalk-box'),underline:el=>el.style.textDecoration='underline wavy #ffd75a',circle:el=>el.style.border='3px solid #8dff9b',crossOut:el=>el.classList.add('cross'),dust:()=>!reduced&&confetti(18),erase:()=>toast('Blackboard eraser wipe!'),stamp:t=>toast('STAMP: '+t),confetti:(n=80)=>confetti(n)};
function go(i){if(i<0||i>=slides.length)return;slides[current].classList.remove('active');current=i;slides[current].classList.add('active');$('#counter').textContent=`${current+1} / ${slides.length}`;$('#sectionIndicator').textContent=slides[current].dataset.section;$('#progressLine').style.width=((current+1)/slides.length*100)+'%';$('#notes').textContent=slides[current].dataset.notes||'Random teacher note: '+randomNote();lastAction=Date.now();beep(380+current*18,.04);$$('.write',slides[current]).forEach(el=>ChalkDraw.write(el));}
function next(){go(Math.min(slides.length-1,current+1))}function prev(){go(Math.max(0,current-1))}
function randomNote(){return ['Perhatikan papan, bukan grup WhatsApp.','Database-nya Spreadsheet. Duduk dulu.','Ini akan keluar di ujian audit.','Yang belakang jangan sort column sembarangan.','Finance likes this number.'][Math.floor(Math.random()*5)]}
function confetti(n=120){const c=$('#confettiCanvas'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let a=Array.from({length:n},()=>({x:Math.random()*c.width,y:-20,r:4+Math.random()*8,v:2+Math.random()*7,w:Math.random()*6-3,col:['#ffd75a','#ff7ab6','#78d8ff','#8dff9b','#f7f0d4'][Math.floor(Math.random()*5)]}));let frames=0;(function loop(){x.clearRect(0,0,c.width,c.height);a.forEach(p=>{p.y+=p.v;p.x+=p.w;x.fillStyle=p.col;x.fillRect(p.x,p.y,p.r,p.r*.55)});if(frames++<170)requestAnimationFrame(loop);else x.clearRect(0,0,c.width,c.height)})()}
function finalShow(){beep(880,.2);confetti(420);$('#finalMsg').style.display='block';['Single Source of Truth Unlocked','Inbox Survivor','Spreadsheet Wizard','Zero Additional Cost Legend','Warkop Moderator','HR Automation Graduate','Communication Factory Activated'].forEach((b,i)=>setTimeout(()=>toast('🏆 '+b),i*450))}
const features=['Pengumuman','Koran Harian','Obrolan Warkop','Lapak Jualan','Agenda','Factory Wire'];features.forEach((f,i)=>{$('#featureCards').insertAdjacentHTML('beforeend',`<button class="feature-card" style="border-color:${['#ffd75a','#78d8ff','#ff7ab6','#8dff9b','#ff6b64','#fff'][i]}">☑ ${f}<br><small>Status: standby</small></button>`)});let activeFeatures=0;$$('.feature-card').forEach(card=>card.onclick=()=>{if(card.classList.contains('active'))return;card.classList.add('active');card.querySelector('small').textContent='Status: active — teacher approved';activeFeatures++;$('#featureMeter').style.width=(activeFeatures/6*100)+'%';toast('⭐ '+card.textContent.split('\n')[0]);if(activeFeatures===6){$('#featureAchievement').textContent='CLASS ACHIEVEMENT UNLOCKED: Communication Factory Activated';confetti(90)}});
$('#startBtn').onclick=()=>{ChalkDraw.dust();next()};$('#breakingBtn').onclick=()=>{$('.ticker').classList.add('fast');$('#breakingMsg').style.color='#ff6b64';beep(900,.12)};$('#approveBtn').onclick=()=>{$('#pending').textContent=Math.max(0,+$('#pending').textContent-1);$('#published').textContent=+$('#published').textContent+1;toast('APPROVED ⭐')};$('#dangerBtn').onclick=()=>toast('Congratulations. You found the feature requested five minutes before demo.');$('#engBtn').onclick=()=>$('#archList').innerHTML='<li>landing.gs</li><li>cms.gs</li><li>rss-fetcher.gs</li><li>email-fetcher.gs</li>';$('#mgmtBtn').onclick=()=>$('#archList').innerHTML='<li>Employee portal</li><li>Admin dashboard</li><li>Automation engine</li><li>Central data source</li>';$('#runaway').onpointerenter=e=>{e.target.style.transform=`translate(${Math.random()*300-150}px,${Math.random()*160-80}px)`};$('#activateBtn').onclick=finalShow;$('#replayBtn').onclick=finalShow;$('#panicBtn').onclick=()=>toast('Relax. It is only a presentation.');$('#soundBtn').onclick=()=>{muted=!muted;$('#soundBtn').textContent=muted?'Muted':'Sound On'};$('#corpToggle').onchange=e=>{document.body.classList.toggle('corporate',e.target.checked);toast(e.target.checked?'SERIOUS CLASS MODE':'FUN CLASS RESTORED')};$('#notesBtn').onclick=()=>{$('#notes').style.display=$('#notes').style.display==='block'?'none':'block'};
$$('.quadrants button').forEach((b,i)=>b.onclick=()=>{$('#gauge').style.width=(i+1)*25+'%';b.classList.add('active')});$('#quiz').onclick=e=>{if(e.target.tagName==='BUTTON'){$('#quizResult').textContent='Semua jawaban benar wins.';confetti(40)}};
function overview(){const o=$('#overview');if(o.style.display==='grid'){o.style.display='none';return}o.innerHTML='';slides.forEach((s,i)=>{const b=document.createElement('button');b.textContent=`${i+1}. ${s.dataset.section}`;b.onclick=()=>{o.style.display='none';go(i)};o.appendChild(b)});o.style.display='grid'}
let konami=[];const K='ArrowUp,ArrowUp,ArrowDown,ArrowDown,ArrowLeft,ArrowRight,ArrowLeft,ArrowRight,b,a';addEventListener('keydown',e=>{lastAction=Date.now();konami.push(e.key);konami=konami.slice(-10);if(konami.join(',')===K)toast('DETENTION MODE ACTIVATED: You edited production spreadsheet without backup.');if(e.target.matches('input,button'))return; if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();next()} if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();prev()} if(e.key==='Home')go(0); if(e.key==='End')go(slides.length-1); if(e.key==='Escape')overview(); if(e.key.toLowerCase()==='f')document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.(); if(e.key.toLowerCase()==='m')$('#soundBtn').click(); if(e.key.toLowerCase()==='n')$('#notesBtn').click(); if(e.key.toLowerCase()==='a'){toast('Audience engagement artificially increased.');confetti(50)} if(e.key.toLowerCase()==='p')document.body.classList.toggle('capture'); if(e.key.toLowerCase()==='d')toggleDraw(); if(e.key.toLowerCase()==='e'){eraser=!eraser;toast(eraser?'Eraser mode':'Chalk mode')} if(e.key.toLowerCase()==='c')clearDraw(); if('123456'.includes(e.key))color=['#f7f0d4','#ffd75a','#ff7ab6','#78d8ff','#8dff9b','#ff6b64'][+e.key-1]; if(e.ctrlKey&&e.key.toLowerCase()==='z')undoDraw(); if(e.key.toLowerCase()==='q')$('#quiz').style.display='grid'});
let wheel=0;addEventListener('wheel',e=>{if(Date.now()-wheel<650)return;wheel=Date.now();e.deltaY>0?next():prev()},{passive:true});let sx=0;addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>50)(dx<0?next:prev)()},{passive:true});
const dc=$('#drawCanvas'),ctx=dc.getContext('2d');function resize(){dc.width=innerWidth;dc.height=innerHeight}resize();addEventListener('resize',resize);function toggleDraw(){drawing=!drawing;dc.classList.toggle('drawing',drawing);toast(drawing?'Presenter chalk drawing mode':'Drawing off')}function clearDraw(){ctx.clearRect(0,0,dc.width,dc.height);strokes=[]}function undoDraw(){strokes.pop();ctx.clearRect(0,0,dc.width,dc.height);strokes.forEach(s=>drawStroke(s,false))}function drawStroke(s,save=true){ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=s.eraser?'#183b2c':s.color;ctx.lineWidth=s.eraser?26:5;ctx.beginPath();s.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();if(save)strokes.push(s)}dc.onpointerdown=e=>{if(!drawing)return;curStroke={color,eraser,points:[{x:e.clientX,y:e.clientY}]}};dc.onpointermove=e=>{if(!drawing||!curStroke)return;curStroke.points.push({x:e.clientX,y:e.clientY});drawStroke(curStroke,false)};dc.onpointerup=()=>{if(curStroke){strokes.push(curStroke);curStroke=null}};
setInterval(()=>{if(Date.now()-lastAction>30000){toast('Operator inactive. Possible causes: meeting, coffee, or existential crisis.');lastAction=Date.now()}},5000);go(0);
