(() => {
  'use strict';
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const slides = $$('.slide'); let index = 0, lastNav = 0, wheelLock = false, sound = true, meetings = 0, idleTimer, numberBuffer = '', touch = {x:0,y:0};
  const progress = $('#progress'), counter = $('#counter'), overview = $('#overview'), notes = $('#notes'), cursor = $('.cursor');
  const achievements = ['Single Source of Truth Unlocked','Inbox Survivor','Spreadsheet Architect','HR Automation Initiated','Warkop Moderator','Budget-Friendly Innovation','Zero Additional Cost Legend'];
  const notifications = ['Spreadsheet survived another day.','Admin approval detected.','No duplicate news found. A miracle.','Calendar successfully reminded everyone about a meeting.','Anonymous user has entered the Warkop.'];
  const featureData = [['📣','Pengumuman','Informasi resmi, countdown, pinned card.'],['📰','Koran Harian','RSS industri otomatis dan terkurasi.'],['☕','Obrolan Warkop','Forum anonim dengan moderasi.'],['🛒','Lapak Jualan','Marketplace UMKM karyawan.'],['📅','Agenda','Meeting pribadi dari Calendar.'],['📡','Factory Wire','Ticker cepat untuk info kilat.']];

  console.log(`====================================\nRUBRIK FACTORY CONTROL SYSTEM\n====================================\nStatus       : ONLINE\nDatabase     : Google Sheets\nInfrastructure Cost : Rp 0\nDeveloper Mood       : Depends on deadline\n====================================`);
  function beep(type='click'){ if(!sound) return; try{ const ctx = new (window.AudioContext||window.webkitAudioContext)(); const o=ctx.createOscillator(), g=ctx.createGain(); o.type= type==='alarm'?'sawtooth':'square'; o.frequency.value = type==='cash'?880:type==='alarm'?180:420; g.gain.value=.035; o.connect(g); g.connect(ctx.destination); o.start(); setTimeout(()=>{o.stop();ctx.close();}, type==='alarm'?260:90);}catch(e){} }
  function clamp(n){ return Math.max(0, Math.min(slides.length-1, n)); }
  function goTo(n, force=false){ const now=Date.now(); if(!force && now-lastNav<260) return; lastNav=now; const next=clamp(n); if(next===index) return; slides[index].classList.remove('active'); index=next; slides[index].classList.add('active'); render(); resetIdle(); meetings += Math.random()>.55?1:0; $('#meetings').textContent=`Meetings avoided by RuBrik: ${meetings}`; if(index%3===0) showAchievement(achievements[(index/3|0)%achievements.length]); if(index===8) $('#clock').textContent='📅 Calendar'; beep(); }
  function render(){ progress.innerHTML=slides.map((_,i)=>`<button class="${i===index?'active':''}" data-slide="${i}" aria-label="Slide ${i+1}"></button>`).join(''); counter.textContent=`${String(index+1).padStart(2,'0')} / ${String(slides.length).padStart(2,'0')}`; $('#sectionIndicator').textContent=slides[index].dataset.section||'RUBRIK'; notes.textContent=slides[index].dataset.notes||'No private speaker notes for this slide.'; }
  function buildOverview(){ overview.innerHTML=slides.map((s,i)=>`<button class="thumb" data-thumb="${i}"><b>${String(i+1).padStart(2,'0')} • ${s.dataset.section}</b>${s.dataset.title||s.querySelector('h2,h1')?.textContent}</button>`).join(''); }
  function toggleOverview(force){ const open = force ?? !overview.classList.contains('open'); overview.classList.toggle('open',open); overview.setAttribute('aria-hidden',String(!open)); }
  function toggleFullscreen(){ document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen?.(); }
  function showAchievement(text){ const el=document.createElement('div'); el.className='badge-pop'; el.textContent='🏆 '+text; $('#achievements').appendChild(el); setTimeout(()=>el.remove(),3100); }
  function notify(text){ const el=document.createElement('div'); el.className='notify'; el.textContent='▣ '+text; $('#notifications').appendChild(el); setTimeout(()=>el.remove(),3300); }
  function resetIdle(){ clearTimeout(idleTimer); $('#idle').classList.remove('show'); idleTimer=setTimeout(()=>$('#idle').classList.add('show'),30000); }
  function setMeter(){ const active=$$('#features article.active').length, val=15+Math.round(active/6*85); $('#effMeter').style.width=val+'%'; $('#effText').textContent=val+'%'; if(active===6){ $('#operational').textContent='FACTORY COMMUNICATION FULLY OPERATIONAL'; smallConfetti(); showAchievement('Single Source of Truth Unlocked'); }}
  function initFeatures(){ $('#features').innerHTML=featureData.map((f,i)=>`<article><span class="led"></span> <b>${f[0]} ${f[1]}</b><p>${f[2]}</p><button data-feature="${i}">SWITCH</button></article>`).join(''); }
  function confetti(count=80, palette=['#f6c542','#ff8a2a','#c94336','#4285f4','#34a853','#ea4335','#fbbc04']){ const c=$('#confetti'), ctx=c.getContext('2d'); c.width=innerWidth; c.height=innerHeight; const parts=Array.from({length:count},()=>({x:Math.random()*c.width,y:-20-Math.random()*c.height,w:6+Math.random()*10,h:8+Math.random()*14,v:2+Math.random()*6,r:Math.random()*6,col:palette[Math.random()*palette.length|0]})); let t=0; function draw(){ ctx.clearRect(0,0,c.width,c.height); parts.forEach(p=>{p.y+=p.v;p.x+=Math.sin((t+p.r)/8)*2;p.r+=.09;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.r);ctx.fillStyle=p.col;ctx.fillRect(-p.w/2,-p.h/2,p.w,p.h);ctx.restore();}); if(t++<240) requestAnimationFrame(draw); else ctx.clearRect(0,0,c.width,c.height); } draw(); }
  window.smallConfetti=()=>confetti(35); window.mediumConfetti=()=>confetti(90); window.massiveConfetti=()=>confetti(260); window.moneyConfetti=()=>confetti(90,['#34a853','#e9f8ee','#137333']); window.googleColorConfetti=()=>confetti(150,['#4285f4','#ea4335','#fbbc04','#34a853']);

  document.addEventListener('mousemove',e=>{ cursor.style.left=e.clientX+'px'; cursor.style.top=e.clientY+'px'; resetIdle(); });
  document.addEventListener('click',e=>{ resetIdle(); const ds=e.target.dataset; if(ds.slide) goTo(+ds.slide,true); if(ds.thumb){toggleOverview(false);goTo(+ds.thumb,true)} if(ds.goto) goTo(+ds.goto,true); if(ds.feature!==undefined){e.target.closest('article').classList.toggle('active');setMeter();beep();} });
  document.addEventListener('keydown',e=>{ resetIdle(); const k=e.key; const seq=['ArrowUp','ArrowUp','ArrowDown','ArrowDown','ArrowLeft','ArrowRight','ArrowLeft','ArrowRight','b','a']; konami.push(k); konami.splice(0,konami.length-10); if(seq.every((v,i)=>konami[i]===v)) overtime(); if(['ArrowRight','PageDown',' '].includes(k)){e.preventDefault();goTo(index+1);} if(['ArrowLeft','PageUp'].includes(k)){e.preventDefault();goTo(index-1);} if(k==='Home')goTo(0,true); if(k==='End')goTo(slides.length-1,true); if(k==='Escape')toggleOverview(); if(k==='f'||k==='F')toggleFullscreen(); if(k==='m'||k==='M')toggleSound(); if(k==='n'||k==='N')notes.classList.toggle('open'); if(k==='a'||k==='A'){smallConfetti();notify('Audience engagement artificially increased.');} if(/^[0-9]$/.test(k)){numberBuffer+=k; clearTimeout(numTimer); numTimer=setTimeout(()=>{ const target=+numberBuffer-1; numberBuffer=''; if(target>=0)goTo(target,true);},450);} }); let konami=[], numTimer;
  document.addEventListener('wheel',e=>{ if(wheelLock||Math.abs(e.deltaY)<25)return; wheelLock=true; goTo(index+(e.deltaY>0?1:-1)); setTimeout(()=>wheelLock=false,700); },{passive:true});
  document.addEventListener('touchstart',e=>{touch.x=e.changedTouches[0].clientX;touch.y=e.changedTouches[0].clientY;},{passive:true});
  document.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touch.x, dy=e.changedTouches[0].clientY-touch.y; if(Math.max(Math.abs(dx),Math.abs(dy))>55) goTo(index+((dx<0||dy<0)?1:-1));},{passive:true});
  $('#prev').onclick=()=>goTo(index-1); $('#next').onclick=()=>goTo(index+1); $('#overviewBtn').onclick=()=>toggleOverview(); $('#fullBtn').onclick=toggleFullscreen; $('#notesBtn').onclick=()=>notes.classList.toggle('open');
  function toggleSound(){ sound=!sound; $('#soundBtn').textContent=sound?'Sound On':'Sound Off'; } $('#soundBtn').onclick=toggleSound;
  $('#panicBtn').onclick=()=>{document.body.classList.add('panic-flash'); notify('Relax. It is only a presentation.'); beep('alarm'); setTimeout(()=>document.body.classList.remove('panic-flash'),1600);};
  $('#corporateMode').onchange=e=>{document.body.classList.toggle('corporate',e.target.checked); notify(e.target.checked?'Corporate Mode enabled. Formality increased.':'Fun restored. Compliance remains intact.');};
  $('#moreMeetings').onchange=e=>{ if(e.target.checked) $('#calendarList').insertAdjacentHTML('beforeend','<p>16:00 Focus Time — moved by someone else</p><p>17:30 Meeting to Discuss Why Project Is Late</p>'); };
  $('#breakingBtn').onclick=()=>{ $('.wire').classList.toggle('breaking-mode'); beep('alarm'); };
  $('#randomWire').onclick=()=>{ const arr=['Spreadsheet survived another day','Forklift of facts arriving','No server was financially harmed','Risol Bu Nandus restocked','Link-nya sudah benar kali ini']; $('#wireText').textContent=arr[Math.random()*arr.length|0]+' • '+$('#wireText').textContent; };
  $('#engineerMode').onclick=()=>$('#arch').innerHTML='<article><b>Presentation Layer</b><p>Landing GAS Project • HTML • CSS • JS</p></article><article><b>Logic Layer</b><p>landing.gs • cms.gs • rss-fetcher.gs • email-fetcher.gs</p></article><article><b>Data Layer</b><p>Shared Spreadsheet ID • Sheets • Drive • Gmail • Calendar</p></article>';
  $('#mgmtMode').onclick=()=>$('#arch').innerHTML='<article><b>Employee portal</b><p>Tempat karyawan membaca informasi.</p></article><article><b>Admin dashboard</b><p>Tempat HR mengelola konten.</p></article><article><b>Central data source</b><p>Satu sumber data yang sama.</p></article>';
  $('#approveBtn').onclick=()=>{ $('#pendingCount').textContent=Math.max(0,+$('#pendingCount').textContent-1); $('#pubCount').textContent=+$('#pubCount').textContent+1; $('#cmsToast').classList.add('show'); smallConfetti(); setTimeout(()=>$('#cmsToast').classList.remove('show'),900); };
  $('#doNotClick').onclick=()=>notify('Congratulations. You found the feature requested five minutes before demo.');
  $('#deleteSheet').onmouseover=()=>{ const b=$('#deleteSheet'); b.style.transform=`translate(${Math.random()*260-130}px,${Math.random()*140-70}px)`; beep('alarm'); };
  $$('.strategy button').forEach(btn=>btn.onclick=()=>{btn.classList.add('active'); const v=$$('.strategy button.active').length*25; $('#signalGauge').style.width=v+'%'; $('#signalText').textContent=v+'%';});
  $$('.poll-options button').forEach(btn=>btn.onclick=()=>{$('#pollResult').classList.add('show'); mediumConfetti();});
  $('#activateBtn').onclick=()=>{ $('#finalCelebration').classList.add('show'); massiveConfetti(); googleColorConfetti(); beep('cash'); showAchievement('COMMUNICATION FACTORY ACTIVATED'); };
  $('#replayConfetti').onclick=()=>massiveConfetti(); $('#realityBtn').onclick=()=>$('#realityMsg').textContent='Meeting berikutnya dimulai dalam 5 menit.';
  function overtime(){ document.body.classList.add('overtime'); $('#clock').textContent='23:59'; notify('Deadline detected. Good luck, operator.'); }
  setInterval(()=>{ if(!document.body.classList.contains('overtime') && index!==8) $('#clock').textContent=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}); },1000);
  setInterval(()=>notify(notifications[Math.random()*notifications.length|0]),18000);
  initFeatures(); buildOverview(); render(); resetIdle();
})();
